# Generated by Django 5.0.1 on 2024-01-29 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 22, 18, 17, 551562, tzinfo=datetime.timezone.utc)),
        ),
    ]
