# Generated by Django 5.0.1 on 2024-01-29 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrenda', '0002_alter_entrada_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
